[build]
  publish = "."

[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 200

[[redirects]]
  from = "/pages/reset-password.html"
  to = "/reset-password.html"
  status = 200
